language: python
cache:
  timeout: 3600
  pip: true
  directories:
    - $HOME/.docker
services:
  - docker

_ubuntu_xenial_build: &ubuntu_xenial_build
  docker_image_tag: ubuntu-xenial
  CACHE_NAME: xenial
  TOXENV: functional_stable

_ubuntu_bionic_build: &ubuntu_bionic_build
  docker_image_tag: ubuntu-bionic
  CACHE_NAME: xenial
  TOXENV: functional_stable

_centos_build: &centos_build
  docker_image_tag: centos-7
  CACHE_NAME: cent7
  TOXENV: functional_stable

_opensuse_build: &opensuse_build
  docker_image_tag: opensuse-42.3
  docker_command: /usr/lib/systemd/systemd
  CACHE_NAME: suse43
  TOXENV: functional_stable

env:
  global:
    - ANSIBLE_FORCE_COLOR=1
    - docker_image=quay.io/loganv/docker-ci
    - docker_command=/lib/systemd/systemd
    - cache_dir=$HOME/.docker

matrix:
  fast_finish: true
  include:
    - env:
        TOXENV: linters
        CACHE_NAME: linters
    # ANSIBLE 2.3
    - env:
        <<: *ubuntu_xenial_build
        TOXENV: functional_2.3
    - env:
        <<: *ubuntu_bionic_build
        TOXENV: functional_2.3
    - env:
        <<: *centos_build
        TOXENV: functional_2.3
    - env:
        <<: *opensuse_build
        TOXENV: functional_2.3
    # ANSIBLE 2.4
    - env:
        <<: *ubuntu_xenial_build
        TOXENV: functional_2.4
    - env:
        <<: *ubuntu_bionic_build
        TOXENV: functional_2.4
    - env:
        <<: *centos_build
        TOXENV: functional_2.4
    - env:
        <<: *opensuse_build
        TOXENV: functional_2.4
    # ANSIBLE 2.5
    - env:
        <<: *ubuntu_xenial_build
        TOXENV: functional_2.5
    - env:
        <<: *ubuntu_bionic_build
        TOXENV: functional_2.5
    - env:
        <<: *centos_build
        TOXENV: functional_2.5
    - env:
        <<: *opensuse_build
        TOXENV: functional_2.5
    # ANSIBLE STABLE
    - env:
        <<: *ubuntu_xenial_build
    - env:
        <<: *ubuntu_bionic_build
    - env:
        <<: *centos_build
    - env:
        <<: *opensuse_build

before_install:
  # Load cached docker images
  - if [[ -d ${cache_dir} ]]; then ls ${cache_dir}/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - if [[ -n ${docker_image_tag} ]]; then docker pull ${docker_image}:${docker_image_tag}; fi
install:
  - pip install tox
before_script:
  - curl -o ${PWD}/tox.ini https://gist.githubusercontent.com/Logan2211/c5f38423b085fbea78392f1ee10700d5/raw/tox.ini
script:
  - tox
before_cache:
  # Save tagged docker images
  - >
    mkdir -p ${cache_dir} && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e ${cache_dir}/$1.tar.gz || docker save $0 | gzip -2 > ${cache_dir}/$1.tar.gz'
notifications:
  email: false
  slack:
    rooms:
      secure: rATdUHj3tZvC0bJVe/t0+Dbfgb6+huZYttgFEOXH+plagwwcIpa8JsvKP9jiAe0D0HTL4haPB4cK7JxJNK7/utup7z4VvIWfU1YuhaZFOYyjOQ/FHeu1m8PpMtc4d7ehTVKeZkPfj7aJ3qN/jMFOWQ6QKM1Aqo5EdhStMhlbpXRrQEDLq9C/veI7M8rvOveduoo5KZ5jC+sX25K03C1afUEBntqLXnFPJlBYYrVCqcEhS0v2CmZeZofI31zl2PLLEmJtUtyGXm7w699Aefsy0jeKcoiyxfn13fAMXXFuZZQP245L8KLbKu+z5EknXaSQdyGMycpoV2YKaTQujaNYO27DsWqbn41U6gR5RS+ywyQ6f9hWajGVip3cMD/awn27qviwL2EwF/kQUtdiw5j3a1sX2fAspG+UiA+sIF4le8WX7OxA6YLguF6esT24ilGqAHiOs2UJ6z9CWAHOK3+SwskX5FcljIHMPVi4stcyiKZSDzpcbxfW6ptpTEKujJKoudmI/m8jCaa5tDBNpUz3lUpxY4NE+8EzMq0EKomTKlXFRGVe2g/b4i5a3cLXpaM7aKAnl0WVKolAsVymPwbiv9msCfgrB3UvwBoLlboaI5Swf5LC/J2HDWqg1Mue8Z0pRX+IS2+SE7aMhgV3Zwn3SWiQ5H1m5P1yLdyA/0z+kaQ=
