---

- name: Add bird apt-keys
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    state: "present"
  with_items: bird_gpg_keys
  register: add_keys
  until: add_keys|success
  retries: 5
  delay: 2
  tags:
    - bird-apt-keys

- name: Add bird apt-keys using fallback keyserver
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.fallback_keyserver }}"
    state: "present"
  register: add_keys_fallback
  until: add_keys_fallback|success
  retries: 5
  delay: 2
  with_items: bird_gpg_keys
  when: add_keys|failed and item.fallback_keyserver is defined
  tags:
    - bird-apt-keys

- name: Add bird repo(s)
  apt_repository:
    repo: "{{ bird_apt_repo.repo }}"
    state: "{{ bird_apt_repo.state }}"
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - bird-repos
