---

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  tags:
    - bird-apt-packages

- name: Install bird apt packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: bird_apt_packages
  tags:
    - bird-apt-packages
