---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Drop bird configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results
  when:
    - "{{ hostvars[inventory_hostname]['ansible_default_' + item.network] is defined }}"
    - "{{ hostvars[inventory_hostname]['ansible_default_' + item.network]['scope'] == 'global' if item.network == 'ipv6' else True }}"
  with_items:
    - { src: "bird.conf.j2", dest: "/etc/bird/bird.conf", network: "ipv4", service: "bird" }
    - { src: "bird6.conf.j2", dest: "/etc/bird/bird6.conf", network: "ipv6", service: "bird6" }
  tags:
    - bird-config

- name: Disable inactive BIRD BGP services and remove from bootup start
  service:
   name: "{{ item.service }}"
   enabled: no
   state: stopped
  when:
    - "{{ hostvars[inventory_hostname]['ansible_default_' + item.network] is not defined
       or (hostvars[inventory_hostname]['ansible_default_' + item.network]['scope'] != 'global' if item.network == 'ipv6' else False) }}"
  with_items:
    - { service: bird, network: ipv4 }
    - { service: bird6, network: ipv6 }
  tags:
    - upstart-init
    - bird-init

- name: Start active BIRD BGP services and add to bootup start
  service:
   name: "{{ item.service }}"
   enabled: yes
   state: started
  when:
    - "{{ hostvars[inventory_hostname]['ansible_default_' + item.network] is defined }}"
    - "{{ hostvars[inventory_hostname]['ansible_default_' + item.network]['scope'] == 'global' if item.network == 'ipv6' else True }}"
  with_items:
    - { service: bird, network: ipv4 }
    - { service: bird6, network: ipv6 }
  tags:
    - upstart-init
    - bird-init

- name: Restart bird services
  service:
    name: "{{ item.item.service }}"
    state: restarted
  when: item.changed
  with_items: bird_results.results
  tags:
    - upstart-init
    - bird-init
