---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "${docker_image:-quay.io/loganv/docker-ci}:${docker_image_tag:-ubuntu-xenial}"
    # NOTE(logan): Uncomment user arg once upstream PR is released
    # https://github.com/metacloud/molecule/pull/1526
    # user: root
    command: ${docker_command:-/lib/systemd/systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    # NOTE(logan): Use custom create playbook with user: root until upstream
    # merges https://github.com/metacloud/molecule/pull/1526
    create: create.yml
    converge: playbook.yml
scenario:
  name: default
